### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Kokecena** [hendriks73/ffsampledsp#12] opened 2021-11-25 00:48 UTC
I am trying to use your library and I follow the instructions as it comes on the page, I only put the dependency inside the POM but when loading an MP3 it throws me
```java.lang.UnsatisfiedLinkError: no ffsampledsp-x86_64-win in java.library.path```
Did I do something wrong or did I skip a step?

**Comment by hendriks73** [comment] 2021-11-25 08:00
What does your POM look like?
Have you built the library locally at some point?

**Comment by hendriks73** [comment] 2021-11-25 13:00
Thanks for pointing me to this issue - it's the packaging that went wrong (I have recently updated the whole build pipeline and moved it to GitHub actions).

I believe the issue is fixed in 0.9.38, available later today or tomorrow.

**Comment by hendriks73** [comment] 2021-11-25 13:08
> I believe the issue is fixed in 0.9.38, available later today or tomorrow.

Hm. Perhaps not 0.9.38, simply because Sonatype is causing issues.

**Comment by hendriks73** [comment] 2021-11-25 15:11
Please try version 0.9.41, when it is available later today or tomorrow.

Thanks.

**Comment by hendriks73** [comment] 2021-11-27 12:49
Is the issue solved, @Kokecena ?

**Comment by Kokecena** [comment] 2021-11-27 22:06
> Is the issue solved, @Kokecena ?

@hendriks73 I apologize for not answering, I delayed building my gamer PC haha, yesterday I checked and version 37 came out, today I checked again and it continues to come out ..., is it that there are still problems with Sonatype?

Sorry for my bad english :p , it is basic and i use google traductor

**Comment by Kokecena** [comment] 2021-11-27 22:22
@hendriks73 I was reviewing the commits and the last one you tried to do, 41, did not pass all the tests

**Comment by Kokecena** [comment] 2021-11-27 22:46
Netbeans confused me, I tried placing version 41 and I loaded it correctly, but now it sends me this error
``` 
nov 27, 2021 4:37:45 PM com.tagtraum.ffsampledsp.FFNativeLibraryLoader arch
INFORMACIÓN: Using arch=x86_64
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer; 
```
Version ```0.9.32``` works fine for me, I just want to make a basic player, but I will be aware of the updates you make and I will tell you if it sends any errors.

**Comment by hendriks73** [comment] 2021-11-28 08:51
On which Java version do you observe this?

**Comment by Kokecena** [comment] 2021-11-28 19:40
@hendriks73 I use version 8

**Comment by Kokecena** [comment] 2021-11-29 01:39
Sorry for the delay, I tried compiling the project with JDK 16 and played songs without problems, I only have problems running it in version 8

**Comment by hendriks73** [comment] 2021-11-30 12:29
Ah. That's because of the covariant return type introduced in Java 9. See for example https://github.com/eclipse/jetty.project/issues/3244

v0.9.43 should fix the issue (available today or tomorrow).

**Comment by hendriks73** [comment] 2021-12-01 09:26
@Kokecena Did it work for you? Can I close this issue?

**Comment by Kokecena** [comment] 2021-12-01 09:58
Yes, it already works perfectly in Java 8 it no longer sends me an error attached to an image playing a song, thanks for solving this problem
![image](https://user-images.githubusercontent.com/75457600/144212933-1d7cfcb4-db76-41fb-b753-9cdeaf272f67.png)

**Comment by hendriks73** [comment] 2021-12-01 10:01
Thanks for making me aware of it!

**Closed by hendriks73** 2021-12-01 10:01 UTC
